# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI sync suppliers to lark

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  sync-job:
    runs-on: ubuntu-latest
    environment: sync_kiot_to_lark

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run sync-suppliers.js
        env:
          KIOT_SECRET: ${{ secrets.KIOT_SECRET }}
          KIOT_CLIENT_ID: ${{ secrets.KIOT_CLIENT_ID }}
          KIOTVIET_RETAILER: ${{ secrets.KIOTVIET_RETAILER }}
          LARK_APP_ID: ${{ secrets.LARK_APP_ID }}
          LARK_APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
          DATABASE_URL_NEON_DB: ${{ secrets.DATABASE_URL_NEON_DB }}
          DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
          AES_256_CBC_APP_SECRET_KEY: ${{ secrets.AES_256_CBC_APP_SECRET_KEY }}
          LARK_BASE_ID: ${{ vars.LARK_BASE_ID }}
          LARK_TABLE_SUPPLIERS_NAME: ${{ vars.LARK_TABLE_SUPPLIERS_NAME }}

        run: node sync-suppliers.js